rule all:
    input:
        "vill_train.tre",
        "vill_1.tre",
        "vill_2.tre",
        "vill_3.tre",
        "vill_4.tre"

rule fasttree:
    input:
        "../../data/{dataset}.fas"
    output:
        "{dataset}.tre"
    shell:
        "fasttree -nt -gtr {input} > {output}"

