rule all:
    input:
        "vill_train.nwk",
        "vill_1.nwk",
        "vill_2.nwk",
        "vill_3.nwk",
        "vill_4.nwk"

rule fasttree:
    input:
        "../../data/{dataset}.fas"
    output:
        "{dataset}.nwk"
    shell:
        "fasttree -nt -gtr {input} > {output}"

